fix #3 create packaging/installation setup for Mac
coding-blocks/Snipper pull request #4
Opened 2017-06-03 18:15 UTC by shubhamvashisht

To build for mac, Run --->   npm run dist-mac

2017-06-03 18:41 UTC, piyush0 commented
![screen shot 2017-06-04 at 12 09 54 am](https://cloud.githubusercontent.com/assets/20954567/26756173/540927f8-48ba-11e7-97e6-5d65cbe3db58.png)

Getting this error. Please check

2017-06-03 20:42 UTC, shubhamvashisht commented
I forgot to add,
first you will have to install [Electron Builder](https://www.npmjs.com/package/electron-builder]) to build the project.
1. Run--->   `npm install electron-builder --save-dev` to install electron builder.
then
2. Run--->  `npm run dist-mac` to build.

2017-06-03 21:01 UTC, piyush0 commented
👍 
@championswimmer Reviewed this. Ready to merge.

2017-06-04 11:50 UTC, championswimmer requested changes

2017-06-04 11:50 UTC, championswimmer commented on package.json
> +    "electron-builder": "^18.3.5"
indendation

2017-06-04 11:50 UTC, championswimmer commented on package.json
> +    "appId": "coding-blocks.Snipper",
can an App Icon be also added (use a dummy square icon of CB for now, we will design a icon separately later)

2017-06-04 19:48 UTC, shubhamvashisht commented
1. Icon for mac package added.
2. Indentation fixed.

2017-06-05 08:37 UTC, merged