#2 and #3 Electron Packager/installer for windows and mac
coding-blocks/Snipper pull request #6
Opened 2017-06-04 09:38 UTC by adarsh1021

1. Install the app by running (Now this also installs the required electron packager and installers) :  
npm install

2. To build run : 
npm run package-win
npm run package-mac

3.  To create installer files run : 
npm run create-installer-win
npm run create-installer-mac

I tested on windows. Working well.

2017-06-04 18:14 UTC, championswimmer requested changes

2017-06-04 18:14 UTC, championswimmer commented on package.json
> +    "electron": "^1.4.3",
already in dependencies. remove electron from dependencies, and update the version to 1.6.6 here

2017-06-05 09:14 UTC, piyush0 commented
@adarsh1021 Since build for mac has already been solved in #4. Remove all changes that are associated with mac so as to avoid any confusion

2017-06-05 17:48 UTC, piyush0 commented
Did you run it after building ? I tested it on windows 64 bit. The build was successful but I am getting this error on running Snipper 
![image](https://cloud.githubusercontent.com/assets/20954567/26795945/2b4403d8-4a45-11e7-8209-8ac605be784b.png)

2017-06-06 09:50 UTC, adarsh1021 commented
I did not run the application. Sorry about that. Since I had not made any changes to the main source code I thought it would be fine.
The issue was a small filename error which I have renamed now. 
On running on my system (win10 64bit) I am getting this error, but I think this is because I have not setup the database. 
![first](https://cloud.githubusercontent.com/assets/22254286/26823462/5b09f5b0-4acb-11e7-834f-bc743ab44411.png)
On clicking OK I get this, so should work fine on your system. 
![second](https://cloud.githubusercontent.com/assets/22254286/26823563/b586d94a-4acb-11e7-9358-002580c977d8.png)

2017-07-13 18:04 UTC, championswimmer commented
conflicts need resolution

2017-07-17 15:14 UTC, closed without merging